version: '3.3'

services:
  postgres:
    image: postgres:15
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5433:5433'
    volumes:
      - postgres_data:/var/lib/postgresql/data
  pgadmin:
    image: dpage/pgadmin4
    environment:
     - PGADMIN_DEFAULT_EMAIL=admin@mail.com
     - PGADMIN_DEFAULT_PASSWORD=123456
    ports:
      - '5050:80'
    depends_on:
      - postgres

volumes:
  postgres_data: {}